apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cnet-tt-yyer-j
  janus-idp.io/tekton: cnet-tt-yyer-j
  backstage.io/kubernetes-id: cnet-tt-yyer-j
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cnet-tt-yyer-j
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
