apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cnet-tt-yyer-j
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnet-tt-yyer-j 
  name: cnet-tt-yyer-j
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cnet-tt-yyer-j 
